server:
  port: 8088
  servlet:
    context-path: /api
    session:
      cookie:
        # cookie30天过期，单位秒
        max-age: 2592000

spring:
  application:
    name: intelligent-picture-service
  session:
    store-type: redis
    # 会话30天过期，单位秒
    timeout: 2592000
  # 文件上传配置
  servlet:
    multipart:
      max-file-size: 10MB
  #指定运行环境
  profiles:
    active: dev
# knife4j接口文档配置
knife4j:
  enable: true
  openapi:
    title: 智能云图库官方文档
    description: 智能云图库官方文档
    version: v1.0
    group:
      default:
        api-rule: package
        api-rule-resources:
          - com.picture.backend.controller
# mybatis-plus配置
mybatis-plus:
  configuration:
    # MyBatis 配置
    map-underscore-to-camel-case: false
    # 仅在开发阶段才打印日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      # 逻辑删除字段
      logic-delete-field: isDelete
      logic-delete-value: 1
      logic-not-delete-value: 0